series: GLFW Graphics
title: Skybox
author:
  name: IGME-RIT
  email:
  github: igme-rit
description: This example demonstrates rendering a skybox.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: GLFW Graphics
    title: Normal Mapping
